{
 "title": "Builders Comparison",
 "description": "Geth metrics overview dashboard.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(chain_head_block{client_name=\"$client_name\"},role)"
    }
   },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   },
   { "name": "rate", "query": "1m, 2m, 5m" },
   { "name": "client_name", "label": "Client", "query": "geth" }
  ]
 },
 "panels": [
  {
   "title": "Blocks Profit Total (Wei)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "miner_block_profit_gauge{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Blocks Profit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(miner_block_profit_gauge{client_name=~\"$client_name\", role=~\"$instance\"}[$rate]) / 1000000000",
     "legendFormat": "build {{role}}"
    }
   ]
  },
  {
   "title": "Blocks Build Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(miner_block_build_count{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "build {{role}}"
    },
    {
     "expr": "rate(miner_block_merge_count{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "merge {{role}}"
    }
   ]
  },
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "engine_newPayloadV2 calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(rpc_duration_engine_newPayloadV2_success_count{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "success {{role}}"
    },
    {
     "expr": "rate(rpc_duration_engine_newPayloadV2_failure_count{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "failure {{role}}"
    }
   ]
  },
  {
   "title": "Durations of successful engine_newPayloadV2 calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rpc_duration_engine_newPayloadV2_success{quantile=\"$quantile\", client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Durations of failed engine_newPayloadV2 calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rpc_duration_flashbots_validateBuilderSubmissionV2_failure{quantile=\"$quantile\", client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "{{role}}"
    }
   ]
  }
 ]
}