{
 "title": "Geth Builder Overview",
 "description": "Geth metrics overview dashboard.",
 "time": { "from": "2023-11-01T16:40:10.382Z", "to": "2023-11-01T16:45:47.718Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(chain_head_block{client_name=\"$client_name\"},role)"
    }
   },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   },
   { "name": "rate", "query": "1m, 2m, 5m" },
   { "name": "client_name", "label": "Client", "query": "geth" }
  ]
 },
 "panels": [
  { "title": "Builder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bids Created Profit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "miner_block_profit_gauge{client_name=~\"$client_name\", role=~\"$instance\"} / 1000000000",
     "legendFormat": "build {{role}}"
    },
    {
     "expr": "beacon_head_slot{role=~\"Proposer\"}",
     "legendFormat": "Slot"
    }
   ]
  },
  {
   "title": "Bids Created",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "miner_block_build{client_name=~\"$client_name\", role=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "build {{role}}"
    },
    {
     "expr": "miner_block_merge{client_name=~\"$client_name\", role=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "merge {{role}}"
    },
    {
     "expr": "beacon_head_slot{role=~\"Proposer\"}",
     "legendFormat": "Slot"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_sysload{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "system {{role}}"
    },
    {
     "expr": "system_cpu_syswait{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "iowait {{role}}"
    },
    {
     "expr": "system_cpu_procload{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "geth {{role}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_memory_allocs{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "alloc {{role}}"
    },
    {
     "expr": "system_memory_used{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "used {{role}}"
    },
    {
     "expr": "system_memory_held{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "held {{role}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "read {{role}}"
    },
    {
     "expr": "rate(system_disk_writebytes{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "write {{role}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "ingress {{role}}"
    },
    {
     "expr": "rate(p2p_egress{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "egress {{role}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "p2p_peers{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "peers {{role}}"
    },
    {
     "expr": "rate(p2p_dials{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "dials {{role}}"
    },
    {
     "expr": "rate(p2p_serves{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "serves {{role}}"
    }
   ]
  },
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(chain_head_header{client_name=~\"$client_name\", role=~\"$instance\"})",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "chain_head_header{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "header {{role}}"
    },
    {
     "expr": "chain_head_receipt{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "receipt {{role}}"
    },
    {
     "expr": "chain_head_block{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "block {{role}}"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(chain_head_receipt{client_name=~\"$client_name\", role=~\"$instance\"})",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(chain_head_block{client_name=~\"$client_name\", role=~\"$instance\"})",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_pending{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "executable {{role}}"
    },
    {
     "expr": "txpool_queued{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "gapped {{role}}"
    },
    {
     "expr": "txpool_local{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "local {{role}}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_queued{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_local{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "chain_execution{quantile=\"$quantile\", client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "execution (q=$quantile) {{role}}"
    },
    {
     "expr": "chain_validation{quantile=\"$quantile\", client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "validation (q=$quantile) {{role}}"
    },
    {
     "expr": "chain_write{quantile=\"$quantile\", client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "commit (q=$quantile) {{role}}"
    },
    {
     "expr": "chain_account_reads{quantile=\"$quantile\", client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "account read (q=$quantile) {{role}}"
    },
    {
     "expr": "chain_account_updates{quantile=\"$quantile\", client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "account update (q=$quantile) {{role}}"
    },
    {
     "expr": "chain_account_hashes{quantile=\"$quantile\", client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "account hashe (q=$quantile) {{role}}"
    },
    {
     "expr": "chain_account_commits{quantile=\"$quantile\", client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "account commit (q=$quantile) {{role}}"
    },
    {
     "expr": "chain_storage_reads{quantile=\"$quantile\", client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "storage read (q=$quantile) {{role}}"
    },
    {
     "expr": "chain_storage_updates{quantile=\"$quantile\", client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "storage update (q=$quantile) {{role}}"
    },
    {
     "expr": "chain_storage_hashes{quantile=\"$quantile\", client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "storage hashe (q=$quantile) {{role}}"
    },
    {
     "expr": "chain_storage_commits{quantile=\"$quantile\", client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "storage commit (q=$quantile) {{role}}"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(txpool_valid{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "valid {{role}}"
    },
    {
     "expr": "rate(txpool_invalid{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "invalid {{role}}"
    },
    {
     "expr": "rate(txpool_underpriced{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "underpriced {{role}}"
    },
    {
     "expr": "rate(txpool_pending_discard{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "executable discard {{role}}"
    },
    {
     "expr": "rate(txpool_pending_replace{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "executable replace {{role}}"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "executable ratelimit {{role}}"
    },
    {
     "expr": "rate(txpool_pending_nofunds{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "executable nofunds {{role}}"
    },
    {
     "expr": "rate(txpool_queued_discard{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "gapped discard {{role}}"
    },
    {
     "expr": "rate(txpool_queued_replace{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "gapped replace {{role}}"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "gapped ratelimit {{role}}"
    },
    {
     "expr": "rate(txpool_queued_nofunds{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "gapped nofunds {{role}}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_disk_read{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "leveldb read {{role}}"
    },
    {
     "expr": "rate(eth_db_chaindata_disk_write{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "leveldb write {{role}}"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_read{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "ancient read {{role}}"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_write{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "ancient write {{role}}"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_read{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "leveldb read {{role}}"
    },
    {
     "expr": "eth_db_chaindata_disk_write{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "leveldb write {{role}}"
    },
    {
     "expr": "eth_db_chaindata_ancient_read{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "ancient read {{role}}"
    },
    {
     "expr": "eth_db_chaindata_ancient_write{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "ancient write {{role}}"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_size{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "leveldb {{role}}"
    },
    {
     "expr": "eth_db_chaindata_ancient_size{client_name=~\"$client_name\", role=~\"$instance\"}",
     "legendFormat": "ancient {{role}}"
    }
   ]
  },
  {
   "title": "Trie Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clean cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_clean_read{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "hit {{role}}"
    },
    {
     "expr": "rate(trie_memcache_clean_write{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "miss {{role}}"
    }
   ]
  },
  {
   "title": "Dirty cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_gc_size{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "gc {{role}}"
    },
    {
     "expr": "rate(trie_memcache_flush_size{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "overflow {{role}}"
    },
    {
     "expr": "rate(trie_memcache_commit_size{client_name=~\"$client_name\", role=~\"$instance\"}[$rate])",
     "legendFormat": "commit {{role}}"
    }
   ]
  }
 ]
}